### ISSUE TITLE
InvalidCastException when hosting an ASP.NET Core behind Azure Relay

### ISSUE THREAD

**Issue by rprimora** [Azure/azure-relay-aspnetserver#10]
I have a simple ASP.NET Core application that is listening to a Hybrid Connection. I get an InvalidCastException when using AuthorizeAttribute. I have set up JwtBearerAuthentication and it works fine when the application is running on its own(read: not hosted as a AzureRelay) but if I want to use the authorization behind AzureRelay than I get this problem. The problem is solvable by just removing the [Authorize] attribute but this is not what I want.

NuGet package is Microsoft.Azure.Relay.AspNetCore 1.1.0-preview-20180522-1

This is my code for Program:
```
ConfigurationBuilder config = new ConfigurationBuilder();
config.AddCommandLine(args);
var commandLineConfig = config.Build();

return WebHost
	.CreateDefaultBuilder()
	.ConfigureAppConfiguration((hostingContext, configuration) => configuration.AddCommandLine(args))    
	.UseKestrel(options =>
	{
		var address = IPAddress.Parse(commandLineConfig.GetValue<string>("url"));
		var port = commandLineConfig.GetValue<int>("port");
		options.Listen(address, port, listenOptions =>
		{
			var serverCertificate = LoadCertificate();
			listenOptions.UseHttps(serverCertificate);
		});
	})
	.UseStartup<Startup>()
	.UseAzureRelay(options =>
	{
		options.TokenProvider = TokenProvider.CreateSharedAccessSignatureTokenProvider("{keyName}", "{key}");
		options.UrlPrefixes.Add("sb://{namespace}.servicebus.windows.net/{hybridConnection}");
	}).Build();
```
This is my ConfigureServices method:
```
var url = Configuration.GetValue<string>("url");
var port = Configuration.GetValue<int>("port");
var secret = Configuration.GetValue<string>("secret");

services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
	.AddJwtBearer(options =>
	{
		options.TokenValidationParameters = new TokenValidationParameters()
		{
			ValidateIssuer = true,
			ValidateAudience = true,
			ValidateIssuerSigningKey = true,
			ValidateLifetime = true,
			ValidIssuer = $"https://{url}:{port}",
			ValidAudience = $"https://{url}:{port}",
			IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secret))
		};
	});
services.AddDataLayer();
services.AddMvc(options =>
{
	options.Filters.Insert(0, new CompanyHeaderFilterAttribute());
	options.Filters.Add(new RequireHttpsAttribute());
	options.Filters.Add(new ExceptionFilter());
}).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
services.AddApiVersioning(options =>
{
	options.ApiVersionReader = new HeaderApiVersionReader("mapaz-api-version");
	options.ErrorResponses = new ErrorResponse();
});
```
And finally the Configure method:
```
var options = new RewriteOptions().AddRedirectToHttps(StatusCodes.Status301MovedPermanently, 5000);

app.UseContext();
app.UseAuthentication();
app.UseRewriter(options);
app.UseMvc();
```
This is the error along with the stack trace that I get when I issue a call to my API:

> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Route matched with {action = "GetCompanies", controller = "Account"}. Executing action Mapaz.ERP.InternalApi.Controllers.AccountController.GetCompanies (Mapaz.ERP.InternalApi)
> Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action Mapaz.ERP.InternalApi.Controllers.AccountController.GetCompanies (Mapaz.ERP.InternalApi) in 12.793ms
> Microsoft.Azure.Relay.AspNetCore.MessagePump: Error: ProcessRequestAsync
> 
> System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Relay.AspNetCore.FeatureContext' to type 'Microsoft.AspNetCore.Http.Features.Authentication.IHttpAuthenticationFeature'.
>    at Microsoft.AspNetCore.Http.Features.FeatureCollection.Get[TFeature]()
>    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.UpdateCached[TFeature,TState](TFeature& cached, TState state, Func`2 factory, Int32 revision, Boolean flush)
>    at Microsoft.AspNetCore.Http.DefaultHttpContext.get_User()
>    at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.<AuthenticateAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.<OnAuthorizationAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Microsoft.Azure.Relay.AspNetCore.MessagePump.<ProcessRequestAsync>d__20.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Azure.Relay.AspNetCore.MessagePump.<ProcessRequestAsync>d__20.MoveNext()
> Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 383.4257ms 200 
> Microsoft.Azure.Relay.AspNetCore.MessagePump: Error: ProcessRequestAsync
> 
> System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'Microsoft.Azure.Relay.RelayedHttpListenerResponse'.
>    at Microsoft.Azure.Relay.RelayedHttpListenerResponse.CheckDisposed()
>    at Microsoft.Azure.Relay.RelayedHttpListenerResponse.set_StatusCode(HttpStatusCode value)
>    at Microsoft.Azure.Relay.AspNetCore.Response.set_StatusCode(Int32 value)
>    at Microsoft.Azure.Relay.AspNetCore.MessagePump.SetFatalResponse(RequestContext context, HttpStatusCode status)
>    at Microsoft.Azure.Relay.AspNetCore.MessagePump.<ProcessRequestAsync>d__20.MoveNext()

**Comment by MarcoRossignoli** [comment]
I've got same issue...after some investigation i think that the issue is https://github.com/Azure/azure-relay-aspnetserver/blob/dev/src/Microsoft.Azure.Relay.AspNetCore/StandardFeatureCollection.cs#L21 where server declare to support authentication but it's not implemented. Code look like HttpSysServer implementation...maybe copy paste bug.
However i'm not sure if this server should support or not authentication feature.

/cc @Tratcher @pranavkm let me know if my suspect is correct i could try a fix PR.

**Comment by Tratcher** [comment]
It's a placeholder for User. If you don't support it then HttpContext will supply a default.
https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http.Features/Authentication/IHttpAuthenticationFeature.cs

**Comment by MarcoRossignoli** [comment]
> It's a placeholder for User. If you don't support it then HttpContext will supply a default.

Ok what do you think is the better approach to fix?Now this https://github.com/Azure/azure-relay-aspnetserver/blob/dev/src/Microsoft.Azure.Relay.AspNetCore/StandardFeatureCollection.cs#L90 fail on casting FeatureContext to IHttpAuthenticationFeature

**Comment by Tratcher** [comment]
Removing it should be fine. That collection only exists as a performance optimization.
