### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-relay-aspnetserver#25]
Hi guys,

Do you have an ETA for WebSockets support, is that in the roadmap?

**Comment by dlstucki** [comment]
Azure Relay HybridConnections already have a mechanism for remoting websockets. Can you clarify your scenario?

Protocol: https://docs.microsoft.com/en-us/azure/azure-relay/relay-hybrid-connections-protocol
Library: https://github.com/Azure/azure-relay-dotnet

**Comment by vany0114** [comment]
Hmmm honestly I don't remember, this was almost a year ago, my bad for open an issue so vaguely. I remember I had an issue with windows 7, but I was able to build a .net core app and use Event Grid + Azure Relay to do what I needed.
